export const NAVIGATION_CLEAR_FOCUSED_INPUT_ESCAPE_PRIORITY = 1_100;
export const CHAT_CLEAR_SELECTED_MESSAGES_ESCAPE_PRIORITY = 900;
export const CHAT_BACK_ESCAPE_PRIORITY = 800;
export const CHAT_CLOSE_CONTEXT_MENU_ESCAPE_PRIORITY = 1_000;